//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characters
    {
        public Characters()
        {
            this.CharacterMovelists = new HashSet<CharacterMovelists>();
            this.CharactersMaps = new HashSet<CharactersMaps>();
            this.CharactersMechanics = new HashSet<CharactersMechanics>();
            this.CharPictures = new HashSet<CharPictures>();
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Fraction_id { get; set; }
    
        public virtual ICollection<CharacterMovelists> CharacterMovelists { get; set; }
        public virtual Fractions Fractions { get; set; }
        public virtual ICollection<CharactersMaps> CharactersMaps { get; set; }
        public virtual ICollection<CharactersMechanics> CharactersMechanics { get; set; }
        public virtual ICollection<CharPictures> CharPictures { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
