//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHHelper.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FHHelperDBEntities : DbContext
    {
        public FHHelperDBEntities()
            : base("name=FHHelperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CharacterMovelists> CharacterMovelists { get; set; }
        public DbSet<Characters> Characters { get; set; }
        public DbSet<CharactersMaps> CharactersMaps { get; set; }
        public DbSet<CharactersMechanics> CharactersMechanics { get; set; }
        public DbSet<CharPictures> CharPictures { get; set; }
        public DbSet<Comments> Comments { get; set; }
        public DbSet<Fractions> Fractions { get; set; }
        public DbSet<History> History { get; set; }
        public DbSet<MapPictures> MapPictures { get; set; }
        public DbSet<Maps> Maps { get; set; }
        public DbSet<OtherMechanics> OtherMechanics { get; set; }
        public DbSet<Requests> Requests { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Trainings> Trainings { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
