//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fractions
    {
        public Fractions()
        {
            this.Characters = new HashSet<Characters>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<Characters> Characters { get; set; }
    }
}
