//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int Training_id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Coach_id { get; set; }
        public int User_id { get; set; }
    
        public virtual Trainings Trainings { get; set; }
        public virtual Users Users { get; set; }
    }
}
