//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comments = new HashSet<Comments>();
            this.Comments1 = new HashSet<Comments>();
            this.History = new HashSet<History>();
            this.Requests = new HashSet<Requests>();
            this.Requests1 = new HashSet<Requests>();
            this.Trainings = new HashSet<Trainings>();
            this.Trainings1 = new HashSet<Trainings>();
        }
    
        public int Id { get; set; }
        public string NickName { get; set; }
        public int Role_id { get; set; }
        public string UplayNick { get; set; }
        public Nullable<int> MainCharacter { get; set; }
        public Nullable<double> Raiting { get; set; }
        public string Password { get; set; }
    
        public virtual Characters Characters { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Comments> Comments1 { get; set; }
        public virtual ICollection<History> History { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual ICollection<Requests> Requests1 { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Trainings> Trainings { get; set; }
        public virtual ICollection<Trainings> Trainings1 { get; set; }
    }
}
